[package]
name = "kvs"
version = "0.1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.32.0"
failure = "0.1.5"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"

[dev-dependencies]
assert_cmd = "0.11.0"
float-cmp = "=0.4.0" # FIXME: https://github.com/assert-rs/predicates-rs/issues/78
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
